//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.InteropServices;

namespace SqlBuddy.TemplateTest
{
    public partial class RunFront
	{
		private static string _databaseName;
        
        static RunFront()
        {
            RunFront.DatabaseName = "rrRunFront";
        }

		public static string DatabaseName
        {
            get { return RunFront._databaseName; }
            set 
			{ 
				RunFront._databaseName = value; 

				dbo.SchemaName = dbo.SchemaName;
			}
        }

		public partial class dbo
		{
			private static string _schemaName;
			private static string _prefix;

			static dbo()
			{
				dbo.SchemaName = "dbo";
			}

			public static string SchemaName
			{
				get { return dbo._schemaName; }
				set {
					 dbo._schemaName = value; 
					 _prefix = GetPrefix();
				}
			}
            
            public static string Prefix
            {
                get { return _prefix; }
            }
            
            public partial class Procedures
            {
				//public static SqlCommand AllowedDivisionList()
				//{
				//    Lexer error. Line 2:0 token recognition error at: '-'
				//}            
            
            }

            private static string GetPrefix()
			{
				return RunFront.GetPrefix(SchemaName);
			}
		}

		
		private static string GetPrefix(string schemaName)
		{
			return string.Format("[{0}].[{1}]", DatabaseName, schemaName);
		}
	}
}